setBackgroundColor(colors.black)
setCursorPos(width,height)
write("\140\140\140\140\140\140\140")
setCursorPos(width,height+1)
write("       ")
setCursorPos(width,height+2)
write("       ")
setCursorPos(width,height+3)
write("       ")
setCursorPos(width,height+4)
write("       ")

